# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_main_window.ui',
# licensing of '.\ui_main_window.ui' applies.
#
# Created: Sun Apr 14 15:08:13 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.newTab = QtWidgets.QWidget()
        self.newTab.setObjectName("newTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.newTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.newTableView = QtWidgets.QTableView(self.newTab)
        self.newTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.newTableView.setAlternatingRowColors(True)
        self.newTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.newTableView.setShowGrid(False)
        self.newTableView.setSortingEnabled(True)
        self.newTableView.setObjectName("newTableView")
        self.newTableView.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.newTableView)
        self.tabWidget.addTab(self.newTab, "")
        self.ownedTab = QtWidgets.QWidget()
        self.ownedTab.setObjectName("ownedTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ownedTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ownedTableView = QtWidgets.QTableView(self.ownedTab)
        self.ownedTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ownedTableView.setAlternatingRowColors(True)
        self.ownedTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ownedTableView.setShowGrid(False)
        self.ownedTableView.setSortingEnabled(True)
        self.ownedTableView.setObjectName("ownedTableView")
        self.ownedTableView.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.ownedTableView)
        self.tabWidget.addTab(self.ownedTab, "")
        self.ignoredTab = QtWidgets.QWidget()
        self.ignoredTab.setObjectName("ignoredTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ignoredTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ignoredTableView = QtWidgets.QTableView(self.ignoredTab)
        self.ignoredTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ignoredTableView.setAlternatingRowColors(True)
        self.ignoredTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ignoredTableView.setShowGrid(False)
        self.ignoredTableView.setSortingEnabled(True)
        self.ignoredTableView.setObjectName("ignoredTableView")
        self.ignoredTableView.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.ignoredTableView)
        self.tabWidget.addTab(self.ignoredTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setShortcutVisibleInContextMenu(True)
        self.actionImport.setObjectName("actionImport")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.newTab), QtWidgets.QApplication.translate("MainWindow", "New", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ownedTab), QtWidgets.QApplication.translate("MainWindow", "Owned", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ignoredTab), QtWidgets.QApplication.translate("MainWindow", "Ignored", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.actionImport.setText(QtWidgets.QApplication.translate("MainWindow", "Import", None, -1))
        self.actionImport.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None, -1))

