# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ui_main_window.ui',
# licensing of '.\ui\ui_main_window.ui' applies.
#
# Created: Tue Mar 26 17:23:37 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.newTab = QtWidgets.QWidget()
        self.newTab.setObjectName("newTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.newTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.newTableWidget = QtWidgets.QTableWidget(self.newTab)
        self.newTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.newTableWidget.setAlternatingRowColors(True)
        self.newTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.newTableWidget.setShowGrid(False)
        self.newTableWidget.setObjectName("newTableWidget")
        self.newTableWidget.setColumnCount(6)
        self.newTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.newTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.newTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.newTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.newTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.newTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.newTableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.newTableWidget)
        self.tabWidget.addTab(self.newTab, "")
        self.ownedTab = QtWidgets.QWidget()
        self.ownedTab.setObjectName("ownedTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ownedTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ownedTableWidget = QtWidgets.QTableWidget(self.ownedTab)
        self.ownedTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ownedTableWidget.setAlternatingRowColors(True)
        self.ownedTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ownedTableWidget.setShowGrid(False)
        self.ownedTableWidget.setObjectName("ownedTableWidget")
        self.ownedTableWidget.setColumnCount(6)
        self.ownedTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ownedTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ownedTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ownedTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ownedTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ownedTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ownedTableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.ownedTableWidget)
        self.tabWidget.addTab(self.ownedTab, "")
        self.ignoredTab = QtWidgets.QWidget()
        self.ignoredTab.setObjectName("ignoredTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ignoredTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ignoredTableWidget = QtWidgets.QTableWidget(self.ignoredTab)
        self.ignoredTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ignoredTableWidget.setAlternatingRowColors(True)
        self.ignoredTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ignoredTableWidget.setShowGrid(False)
        self.ignoredTableWidget.setObjectName("ignoredTableWidget")
        self.ignoredTableWidget.setColumnCount(6)
        self.ignoredTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ignoredTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ignoredTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ignoredTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ignoredTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ignoredTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ignoredTableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_4.addWidget(self.ignoredTableWidget)
        self.tabWidget.addTab(self.ignoredTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setShortcutVisibleInContextMenu(True)
        self.actionImport.setObjectName("actionImport")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.newTableWidget.setSortingEnabled(True)
        self.newTableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Anime", None, -1))
        self.newTableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Type", None, -1))
        self.newTableWidget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Number", None, -1))
        self.newTableWidget.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Song", None, -1))
        self.newTableWidget.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Artist", None, -1))
        self.newTableWidget.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "Used in", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.newTab), QtWidgets.QApplication.translate("MainWindow", "New", None, -1))
        self.ownedTableWidget.setSortingEnabled(True)
        self.ownedTableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Anime", None, -1))
        self.ownedTableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Type", None, -1))
        self.ownedTableWidget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Number", None, -1))
        self.ownedTableWidget.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Song", None, -1))
        self.ownedTableWidget.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Artist", None, -1))
        self.ownedTableWidget.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "Used in", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ownedTab), QtWidgets.QApplication.translate("MainWindow", "Owned", None, -1))
        self.ignoredTableWidget.setSortingEnabled(True)
        self.ignoredTableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Anime", None, -1))
        self.ignoredTableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Type", None, -1))
        self.ignoredTableWidget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Number", None, -1))
        self.ignoredTableWidget.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Song", None, -1))
        self.ignoredTableWidget.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Artist", None, -1))
        self.ignoredTableWidget.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "Used in", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ignoredTab), QtWidgets.QApplication.translate("MainWindow", "Ignored", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.actionImport.setText(QtWidgets.QApplication.translate("MainWindow", "Import", None, -1))
        self.actionImport.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None, -1))

